var SELECT_LESSON = 'SELECT_LESSON'
var SELECT_STEP = 'SELECT_STEP'
var TOGGLE_EDITING = 'TOGGLE_EDITING'
var UPDATE_CODE = 'UPDATE_CODE'
var UPDATE_TEXT = 'UPDATE_TEXT'

module.exports = {
  SELECT_LESSON,
  SELECT_STEP,
  TOGGLE_EDITING,
  UPDATE_CODE,
  UPDATE_TEXT
}