var ADD_STEP = 'ADD_STEP'
var DELETE_STEP = 'DELETE_STEP'
var SELECT_LESSON = 'SELECT_LESSON'
var SELECT_STEP = 'SELECT_STEP'
var TOGGLE_EDITING = 'TOGGLE_EDITING'
var UPDATE_LESSON = 'UPDATE_LESSON'
var UPDATE_STEP = 'UPDATE_STEP'

module.exports = {
  ADD_STEP,
  DELETE_STEP,
  SELECT_LESSON,
  SELECT_STEP,
  TOGGLE_EDITING,
  UPDATE_LESSON,
  UPDATE_STEP
}